jkotlinski/durexforth

- docs/forth.tex
small fix for writing byte (not cell word)
> need to write a byte to A register argument location (not cell word)

- forth_src/ls.fs
MORE placement, Zero return from LOADB
> Improve formatting, error management

- CHANGELOG.md
- docs/words.tex
> Documented SEE and subsequent :NONAMEs

- CHANGELOG.md
- forth_src/sprite.fs
> Fixed bug in SP-X! (Thanks @vinej!)

- forth_src/debug.fs
- forth_src/doloop.fs
- forth_src/labels.fs
- forth_src/turnkey.fs
This leaves 530 bytes remaining on the cart!
Sorry for the new PR.  Forced push shenanigans.
> Hid private words of modules

- Makefile
+ allow other disk image formats.  E.g.  make DISK_SUF=d71 deploy
(larger disks = more free blocks available)
> allow other disk image formats (d71, d81)

- interpreter.asm
This is as tight as I can make it.
It doesn't deal with RUN STOP RESTORE.
>  Revert to 2.0.0 RESTORE handling

- CHANGELOG.md
- docs/memmap.tex
- forth_src/v.fs
Two fixes in one merge:
- The text buffer was very awkwardly placed, squeezed between HERE and LATEST.
- Loading a file too big for the buffer would cause out-of-bounds writes.
Closes #366.
> Move V buffer to $a000-$cbfff, check if file too big

- docs/words.tex
I have edited this but not compiled the pdf yet, so it needs testing.
> Documents the pad, fixing #257

- forth_src/base.fs
- math.asm
> Faster division routines

- CHANGELOG.md
- forth_src/format.fs
- math.asm
Fixes issue #222 
First pass.  Works but is a bit bigger.
Forgive the branch misnomer.
> Rewrote UD/MOD in assembly

- interpreter.asm
Now consistent spaces no tabs.
installed EditorConfig in notepad++
> Remedied formatting issues I created in interpreter.asm

- forth_src/base.fs
- forth_src/wordlist.fs
- interpreter.asm
> unify "word not found" error handling

- Makefile
> Batch up c1541 commands to build disk image in one step

- CHANGELOG.md
- Makefile
- docs/words.tex
- forth_src/base.fs
- forth_src/see.fs
- forth_src/test.fs
- forth_src/testsee.fs
Implements a new `SEE` that is good enough to be actually useful. Closes #441
> Revive SEE

- CHANGELOG.md
- Makefile
- asm_src/durexforth.asm
Haven't decided if I really like it or not...
> added durexForth vx.x.x boot message. closes #477

- CHANGELOG.md
- asm_src/disk.asm
- docs_src/words.adoc
- forth_src/dos.fs
> fix LOADB/SAVEB hang on device not present

- CHANGELOG.md
- asm/disk.asm
- asm/interpreter.asm
close_all_logical_files should call CLRCHN .
> CLRCHN after close_all_logical_files in interpreter.asm

- asm/durexforth.asm
Take 2, as per https://github.com/jkotlinski/durexforth/pull/514#issuecomment-1416812515.
> Just a few comments for new readers of the source

- forth/base.fs
- forth/fractals.fs
- forth/sin.fs
- forth/turtle.fs
- manual/intro.adoc
- test/test.fs
Before optimizations, fractals demo took 8946 jiffies = 149 seconds.
> Optimize fractals

- forth/accept.fs
See [discussion](https://github.com/jkotlinski/durexforth/discussions/538#discussioncomment-5898961).
> space-optimize `accept`

- CHANGELOG.md
- forth/asm.fs
- forth/base.fs
- forth/compat.fs
- forth/doloop.fs
- forth/gfx.fs
- forth/iec.fs
- forth/io.fs
- forth/labels.fs
- forth/mml.fs
- forth/open.fs
- forth/sys.fs
- forth/timer.fs
- forth/turtle.fs
- forth/v.fs
- manual/asm.adoc
- manual/tutorial.adoc
- manual/words.adoc
goal: improve conformance with forth-standard.org. closes #559
> add END-CODE, remove ;CODE

- manual/words.adoc
> Update words.adoc typos I introduced.

- manual/memmap.adoc
> 4Update memmap.adoc typo

- asm/compiler.asm
as suggested in https://github.com/jkotlinski/durexforth/issues/578
> optimize LIT
