- Makefile
- docs/.gitignore
- docs/Makefile
- docs/manual.tex
- docs/release_license.tex
- ext/.gitignore
I wanted to know what version of the document I'm reading when I've printed out the document. So, in the PDF, I added a simple page before table of contents that contains:
- release version (uses TAG from Makefile)
- document generation date (uses default formatting)
- MIT license text (from durexforth.asm) with generated end date
(all the LaTeX commands used are from what I learned today, so please let me know if I used poor form)
> added documentation page with:  release name, generated date, license

- Makefile
changes:
+ moved version number inside d64 from disk name to empty seq file name
+ added separators between main program, version file, and additional
source files.
+ added separator after last file.
As it was, the version barely fit inside the disk name and if the
count of version digits was more than 3 it won't fit in the 16
characters for a disk name (e.g.  v1.6.10 is too long).
```
durexforthvX.Y.Z
|              |
1             16
```
> moved version number that is inside d64 from disk name to a file

- Makefile
Reset to default settings in case drive 8 is missing,
or otherwise misconfigured, and enable warp mode.
> Makefile now launches deploy with nice VICE settings

- forth_src/v.fs
This caused the screen to scroll, making some lines disappear.
> Fixes #239 - Some lines in v.fs were too long

- CHANGELOG.md
- Makefile
- compiler.asm
- control.asm
- core.asm
- disk.asm
- docs/anatomy.tex
- docs/memmap.tex
- docs/tutorial.tex
- docs/words.tex
- durexforth.asm
- forth_src/base.fs
- forth_src/debug.fs
- forth_src/test.fs
- forth_src/turnkey.fs
- forth_src/viceutil.fs
- interpreter.asm
- io.asm
- math.asm
- move.asm
Here is an even smaller version of the split dictionary changes.  It is functional except for the cartridge, which requires 212 bytes to be removed from the dictionary.
I have taken care to try to create the smallest possible set of diffs, hence the least number of changes.  There are also changelog and documentation fixes.
I'm not going to close the other one in case you prefer.  Again, I am not in a hurry and do not this change in master any time soon.
> Minimal Split Dictionary, redux

- CHANGELOG.md
- docs/words.tex
- interpreter.asm
The rationale for this change is this:
The new dictionary structure eliminates the relationship between an XT and its header.  It's no longer a question of simple arithmetic to get one from the other.  DOWORDS exists for scanning the headers, yes, but it's essentially replicating the work FIND-NAME did in the first place, and it's complex and slow.
This change increases the binary size slightly, but reduces the code size and increases the speed of any word that seeks to edit the dictionary. NAME>STRING and >XT would be meaningful outside of a DOWORDS lambda.
> FIND-NAME now return a name token per proposal

- CHANGELOG.md
- docs/editor.tex
- docs/memmap.tex
- forth_src/v.fs
There were no instructions as to how to change `bufstart` properly, so I
didn't bother exporting it.
> Shrunk V with DEFER. Fixed bufstart in memory.

- CHANGELOG.md
- docs/words.tex
- forth_src/defer.fs
There's probably a better place to put it, but `HIDE` bridges an important
gap between using deferred words to hide words en masse and just needing
to delete a single private word.
It is an uncomplicated way to remove any kind of word (deferred variables / values are a bit messy?) from the dictionary with no overhead penalty.
> Added HIDE to defer.fs

- CHANGELOG.md
- docs/editor.tex
- forth_src/v.fs
Added keystroke commands: A, R, +, -, HOME, e, C, D, s, S, H, L, M, ^w, f, F
The command set is now much closer to vi.
Refactored keystroke functions for size now that `:noname` is automatic inside a hidden block.
245 bytes free on the cart.  Net 285 byte growth of `v`.
> V Improved

- forth_src/require.fs
I didn't notice this one in the cleanup.
> Hid private word HASH from require.fs

- CHANGELOG.md
- forth_src/gfx.fs
`PEEK` is documented as a graphics word that can be used without any special preparation, but it assumed that the Kernal had already been switched out, causing incorrect results unless the Kernal had already been switched out before it was invoked.
For example:
`$10 clrcol 3 3 plot 3 3 peek .` should output `16`, but instead we get `0`
The only use of `PEEK` that I could find was in `PAINT` inside `gfx.fs` itself; I have updated `PAINT` to work with the fixed `PEEK`.
Alternatively, we could simply document that `PEEK` must be used in conjunction with  `KERNAL-OUT` and `KERNAL-IN`, but changing `PEEK`'s behavior seems more user-friendly :)
> gfx: PEEK should switch out Kernal automatically

- CHANGELOG.md
- docs/tutorial.tex
- forth_src/turnkey.fs
Adjustments to `turnkey` words to produce a better user experience.
Fixes #302 by restoring forth after `save-pack`
Fixes #303 by locating `latest` at a constant 0 byte
Clarifies some documentation
> Fixes #302 and #303

- forth_src/viceutil.fs
- interpreter.asm
Fixes #309. Also fixes a `dowords` bug that caused the lambda to be called on the invalid nametoken at the end of the dictionary.
> Fix #309 by updating dump-labels to use dowords

- Makefile
+ using `make VICE_X64SC=1 ...` will select `x64sc` and also use the
renamed flag for disabling 'confirm on exit' +confirmonexit
> enable Makefile handling of VICE 3.4+ which has x64sc without x64

- Makefile
+ include Git hash in d64 after version string (for traceability)
+ use lower case 'm' in d64 (was 'M') for warning that repo files were modified
as d64 was generated (looks better when listing disk in upper case mode)
+ calculate TAG variables only once using shell command
(previous form was just text in a variable that was not executed
until later during each command which obfuscates the flow)
> include Git hash in d64 ; calculate TAG variables once

- durexforth.asm
Load fails if string at 'basename' is not exactly 4 characters.
> fix bug with load 'base' fixed filename length.

- CHANGELOG.md
- docs/words.tex
- forth_src/io.fs
- forth_src/open.fs
There is no longer any reason to pass file# into IOABORT, since ABORT now closes all open files.
wdyt @Whammo ?
> change signature of OPEN/CHKIN/CHKOUT/IOABORT

- .lvimrc
- disk.asm
- forth_src/base.fs
- forth_src/io.fs
- io.asm
@Whammo - what do you think?
I like this, because now e.g. "10 DEVICE INCLUDE FOO" will give an error message "DEVICE NOT PRESENT".
This could be very helpful.
_errorchread is still used after failed READST - I'm not sure, but right now I'd guess it's not a bad thing.
Probably some improvements should also be done for LOADB/SAVEB, I will have to think about that tomorrow. It's a bit unclear how errors should be managed for those cases. Maybe they should return an `ioresult`, or maybe something else should be done, don't know yet.
> Convert IOABORT to assembly, use it in INCLUDE

- cart.asm
Fixes issue with U64/UII+, and due to how the Simon's BASIC crt works, should not interfer with other platforms (verified on vice)
The fix enables 16k cartridge mode by doing a write to $de00.
> make sure crt is in 16k mode before doing rom to ram copy

- core.asm
Code reduction and overall speed improvement, although `<` is now slower than `>`, the inverse of before.
> Optimized GREATER_THAN, LESS_THAN

- CHANGELOG.md
- forth_src/io.fs
GETIN is required for RS232 receive and is useful for input from the keyboard buffer.
> Adds GETIN to io.fs

- control.asm
- core.asm
- durexforth.asm
Hi!
I found few places where I could squeeze some more bytes or cycles.
EXIT:
2 bytes, 1 cycle saved.
C!:
3 bytes, 3 cycles saved.
C@:
3 bytes, 3 cycles saved.
0=
For numbers 1-$ff, 6 cycles saved.
For numbers $100, $200,... $ff00, 6 cycles more.
Since the former are much more common than the latter, it's statistically a net saving.
Other numbers unaffected.
> Optimize EXIT, C!, C@ and 0=

- CHANGELOG.md
- forth_src/base.fs
- forth_src/mmldemo.fs
- forth_src/see.fs
Make LITS use a byte for string length, thus reducing maximum string length to 255 bytes. Closes #463 
Good: Saves one byte per string definition. Allows reuse of COUNT. Makes behavior more consistent.
Bad: Breaking change. Broke MML examples.
> max S" string length 255 bytes

- CHANGELOG.md
- compiler.asm
- disk.asm
- docs/words.tex
- forth_src/base.fs
- forth_src/sprite.fs
- forth_src/testsee.fs
- interpreter.asm
- io.asm
Change REFILL to standard behavior.
Attempt to fill the input buffer from the input source, returning a true flag if successful.  Return false if EOF is reached. Return false when the input source is a string from EVALUATE.
Closes #244
> Standard-conforming REFILL

- docs_src/anatomy.adoc
- docs_src/config.adoc
- docs_src/editor.adoc
- docs_src/index.adoc
- docs_src/mnemonics.adoc
- docs_src/sid.adoc
- docs_src/tutorial.adoc
- docs_src/words.adoc
Mostly formatting tweaks. The assembly mnemonics page is probably debatable taste. The book doctype adds a title page, which might be desirable to adjust further (e.g. it supports background image).
> Minor edits of AsciiDoc manual

- CHANGELOG.md
- forth/dos.fs
Default channels already set, Typing and seeing it in on screen. before calling ```send-cmd```
>  Superfluous clrchn in SEND-CMD

- forth/base.fs
- forth/format.fs
Instead of moving characters forward, store them going backward.
> optimize `hold`

- CHANGELOG.md
- asm/core.asm
- asm/io.asm
- forth/base.fs
- forth/mml.fs
- forth/mmldemo.fs
- manual/mml.adoc
- manual/words.adoc
S" .( ( now handles multiple lines according to standard.
GETC is removed.
MML strings are now defined using MML"
Closes #539
> Changed S" .( ( , removed GETC

- asm/lowercase.asm
Does only a single cmp instruction in the common case of characters less than 'A'.
> optimize `CHAR_TO_LOWERCASE`

- CHANGELOG.md
- asm/compiler.asm
See [discussion](https://github.com/jkotlinski/durexforth/commit/1fc6551d069c79ee64a8448f87b8545829bf450f#commitcomment-115573545).
> abort with error on empty HEADER name

- forth/base.fs
> factor out `aborts` #579

- forth/iec.fs
- manual/words.adoc
Fixed typo of stack diagramming of IEC words.  Also considering IEC words to use current device rather than stack input.
>  IEC documentation edit
